/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 m249.glb 
Author: Nortenko Dmytro (https://sketchfab.com/leondp)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/m249-saw-scene-1-fbab0e48119f47e6882f531ccbc8c074
Title: M249 SAW scene (1)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Gun(props) {
  const { nodes, materials } = useGLTF('/m249.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[10.065, 0.003, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <group position={[-0.172, -0.289, 0]}>
            <mesh geometry={nodes.ammo_box_2_m249_a_mat_0.geometry} material={materials.m249_a_mat} position={[0.005, 0, 0.029]} />
            <mesh geometry={nodes.cartridge_1_m249_a_mat_0.geometry} material={materials.m249_a_mat} position={[0.001, 0.006, 0.059]} />
            <mesh geometry={nodes.cartridge_2_m249_a_mat_0.geometry} material={materials.m249_a_mat} position={[0.011, -0.008, 0.06]} />
            <mesh geometry={nodes.picatinny_4_m249_a_mat_0.geometry} material={materials.m249_a_mat} position={[0.042, 0.013, 0.062]} />
            <mesh geometry={nodes.cartridge_3_m249_a_mat_0.geometry} material={materials.m249_a_mat} position={[0.015, -0.048, 0.079]} />
            <mesh geometry={nodes.cartridge_4_m249_a_mat_0.geometry} material={materials.m249_a_mat} position={[0.017, -0.06, 0.06]} />
          </group>
          <group position={[0.003, 0, 0.111]}>
            <group position={[-0.003, 0.197, 0.106]}>
              <mesh geometry={nodes.center_bipod_m249_a_mat_0.geometry} material={materials.m249_a_mat} />
              <mesh geometry={nodes.left_bipod_m249_a_mat_0.geometry} material={materials.m249_a_mat} position={[0, 0.001, -0.008]} />
              <mesh geometry={nodes.right_bipod_m249_a_mat_0.geometry} material={materials.m249_a_mat} position={[0, 0.001, -0.008]} />
            </group>
            <mesh geometry={nodes.m249_a_m249_a_mat_0.geometry} material={materials.m249_a_mat} position={[-0.005, -0.081, 0.074]} />
            <mesh geometry={nodes.ammo_box_m249_a_mat_0.geometry} material={materials.m249_a_mat} position={[-0.017, -0.076, -0.011]} />
            <mesh geometry={nodes.picatinny_1_m249_a_mat_0.geometry} material={materials.m249_a_mat} position={[-0.003, -0.147, 0.135]} />
            <mesh geometry={nodes.picatinny_2_m249_a_mat_0.geometry} material={materials.m249_a_mat} position={[-0.037, 0.027, 0.079]} />
            <mesh geometry={nodes.cartridges_m249_a_mat_0.geometry} material={materials.m249_a_mat} position={[-0.058, -0.105, 0.076]} />
            <mesh geometry={nodes['cartridge-belt_m249_a_mat_0'].geometry} material={materials.m249_a_mat} position={[-0.052, -0.113, 0.098]} />
            <mesh geometry={nodes.hand_hold_2_m249_a_mat_0.geometry} material={materials.m249_a_mat} position={[-0.047, 0.026, 0.082]} />
            <mesh geometry={nodes.hand_hold_1_m249_a_mat_0.geometry} material={materials.m249_a_mat} position={[-0.089, 0.036, 0.085]} />
            <mesh geometry={nodes.picatinny_3_m249_a_mat_0.geometry} material={materials.m249_a_mat} position={[-0.003, 0.053, 0.179]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/m249.glb')
